In [ ]:
! python -m pip install tensorflow keras

In [3]:
import numpy
import pandas

from matplotlib import pyplot
import seaborn

import keras

In [4]:
students = pandas.read_csv("../conjuntos/student_habits_performance.csv")

students

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [14]:
x1 = students["age"]
x2 = students["gender"] == "Female"
x3 = students["gender"] == "Other"
x4 = students["study_hours_per_day"]
x5 = students["social_media_hours"]
x6 = students["netflix_hours"]
x7 = students["part_time_job"] == "Yes"

y1 = students["exam_score"]

X = pandas.DataFrame({
    "x1": x1,
    "x2": x2,
    "x3": x3,
    "x4": x4,
    "x5": x5,
    "x6": x6,
    "x7": x7,
}, dtype="float32")

Y = pandas.DataFrame({
    "y1": y1
}, dtype="float32")

X

       x1   x2   x3   x4   x5   x6   x7
0    23.0  1.0  0.0  0.0  1.2  1.1  0.0
1    20.0  1.0  0.0  6.9  2.8  2.3  0.0
2    21.0  0.0  0.0  1.4  3.1  1.3  0.0
3    23.0  1.0  0.0  1.0  3.9  1.0  0.0
4    19.0  1.0  0.0  5.0  4.4  0.5  0.0
..    ...  ...  ...  ...  ...  ...  ...
995  21.0  1.0  0.0  2.6  0.5  1.6  0.0
996  17.0  1.0  0.0  2.9  1.0  2.4  1.0
997  20.0  0.0  0.0  3.0  2.6  1.3  0.0
998  24.0  0.0  0.0  5.4  4.1  1.1  1.0
999  19.0  1.0  0.0  4.3  2.9  1.9  0.0

[1000 rows x 7 columns]

In [15]:
Y

             y1
0     56.200001
1    100.000000
2     34.299999
3     26.799999
4     66.400002
..          ...
995   76.099998
996   65.900002
997   64.400002
998   69.699997
999   74.900002

[1000 rows x 1 columns]

In [25]:
modelo = keras.Sequential([
    keras.Input(shape=(7,)), # 7 - características
    # keras.layers.Dense(16, activation="relu"),
    # keras.layers.Dense(8, activation="relu"), # Oculta: relu
    keras.layers.Dense(1, activation="linear"), # Abierta: linear | Cerrada: sigmoid
])

modelo.compile(
    optimizer="adam", # Stochastic Gradient Descend
    loss="mse", # Abierta: mse | Cerrada: binary_crossentropy
    metrics=["mae"] # Abierta: mae | Cerrada: accuracy
)

modelo.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8 (32.00 B)

 Trainable params: 8 (32.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
modelo.fit(X, Y, epochs=1000)

Epoch 1/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - loss: 6452.9634 - mae: 78.3793
Epoch 2/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step - loss: 6348.3271 - mae: 77.6625
Epoch 3/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - loss: 6084.7876 - mae: 75.8707
Epoch 4/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - loss: 5970.3110 - mae: 75.2898
Epoch 5/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - loss: 5792.7275 - mae: 74.1408
Epoch 6/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - loss: 5792.1719 - mae: 74.0675
Epoch 7/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 5612.7134 - mae: 72.8299
Epoch 8/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - loss: 5478.4282 - mae: 71.8767
Epoch 9/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - loss: 5397.4893 - mae: 71.3421
Epoch 10/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - loss: 5231.3984 - mae: 70.3993
Epoch 11/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - loss: 5093.8652 - mae: 69.1597
Epoch 12/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - loss: 4981.8105 - mae: 68.5542
Epoch 13/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - loss: 4792.5508 - mae: 67.0644
Epoch 14/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step - loss: 4809.6138 - mae: 67.0953
Epoch 15/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - loss: 4575.8315 - mae: 65.4973
Epoch 16/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - loss: 4403.4360 - mae: 64.0861
Epoch 17/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4314.6948 - mae: 63.4103
Epoch 18/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - loss: 4226.1621 - mae: 62.6627
Epoch 19/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - loss: 4154.8389 - mae: 62.2625
Epoch 20/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - loss: 4164.3325 - mae: 62.1561
Epoch 21/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - loss: 3983.4695 - mae: 60.8831
Epoch 22/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - loss: 3824.0232 - mae: 59.5430
Epoch 23/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - loss: 3689.4900 - mae: 58.3338
Epoch 24/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - loss: 3575.5300 - mae: 57.2276
Epoch 25/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step - loss: 3542.8599 - mae: 57.0487
Epoch 26/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - loss: 3409.4402 - mae: 55.9636
Epoch 27/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - loss: 3374.1113 - mae: 55.5894
Epoch 28/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 748us/step - loss: 3171.3594 - mae: 53.6878
Epoch 29/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3136.4417 - mae: 53.3273
Epoch 30/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - loss: 3074.2668 - mae: 52.7472
Epoch 31/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - loss: 2948.7334 - mae: 51.4378
Epoch 32/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - loss: 2840.2268 - mae: 50.6169
Epoch 33/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - loss: 2886.0503 - mae: 51.1526
Epoch 34/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step - loss: 2778.6118 - mae: 50.0441
Epoch 35/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - loss: 2654.3091 - mae: 48.5701
Epoch 36/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - loss: 2600.9062 - mae: 48.1371
Epoch 37/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step - loss: 2545.4519 - mae: 47.6527
Epoch 38/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - loss: 2415.3748 - mae: 46.3650
Epoch 39/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 748us/step - loss: 2455.8667 - mae: 46.8273
Epoch 40/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - loss: 2301.1570 - mae: 44.8424
Epoch 41/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 764us/step - loss: 2194.9902 - mae: 43.7785
Epoch 42/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - loss: 2225.2131 - mae: 44.1350
Epoch 43/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - loss: 2138.7612 - mae: 43.1287
Epoch 44/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - loss: 2066.4211 - mae: 42.2558
Epoch 45/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - loss: 2001.3134 - mae: 41.5960
Epoch 46/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - loss: 1965.4202 - mae: 41.2554
Epoch 47/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - loss: 1819.1458 - mae: 39.3590
Epoch 48/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 1854.1611 - mae: 39.9588
Epoch 49/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step - loss: 1862.3743 - mae: 39.9701
Epoch 50/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step - loss: 1742.6963 - mae: 38.3711
Epoch 51/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step - loss: 1691.1304 - mae: 37.7031
Epoch 52/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - loss: 1624.4155 - mae: 37.0405
Epoch 53/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - loss: 1568.1874 - mae: 36.2678
Epoch 54/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - loss: 1543.6165 - mae: 35.7117
Epoch 55/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - loss: 1486.1561 - mae: 34.9871
Epoch 56/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - loss: 1462.4580 - mae: 34.9128
Epoch 57/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 1414.5916 - mae: 34.1367
Epoch 58/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - loss: 1378.6210 - mae: 33.3840
Epoch 59/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - loss: 1311.8608 - mae: 32.3275
Epoch 60/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - loss: 1289.8647 - mae: 32.2031
Epoch 61/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - loss: 1245.0493 - mae: 31.5951
Epoch 62/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - loss: 1159.1781 - mae: 30.3138
Epoch 63/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - loss: 1158.7426 - mae: 30.3060
Epoch 64/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - loss: 1118.7363 - mae: 29.4732
Epoch 65/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - loss: 1085.6100 - mae: 28.8147
Epoch 66/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - loss: 1047.3485 - mae: 28.5021
Epoch 67/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - loss: 1019.7431 - mae: 28.0936
Epoch 68/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - loss: 948.7645 - mae: 26.8395
Epoch 69/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - loss: 951.5867 - mae: 26.9255
Epoch 70/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - loss: 959.8612 - mae: 27.0880
Epoch 71/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - loss: 883.8845 - mae: 25.6604
Epoch 72/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 702us/step - loss: 873.6307 - mae: 25.8182
Epoch 73/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - loss: 892.8810 - mae: 25.9550
Epoch 74/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - loss: 839.4728 - mae: 24.9454
Epoch 75/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step - loss: 765.7848 - mae: 23.7213
Epoch 76/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 773us/step - loss: 810.1056 - mae: 24.5230
Epoch 77/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - loss: 745.0703 - mae: 23.4521
Epoch 78/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - loss: 727.6879 - mae: 22.9699
Epoch 79/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - loss: 719.6172 - mae: 22.8347
Epoch 80/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - loss: 705.4183 - mae: 22.7053
Epoch 81/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - loss: 656.8410 - mae: 21.7638
Epoch 82/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - loss: 653.7485 - mae: 21.8091
Epoch 83/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step - loss: 641.7269 - mae: 21.5474
Epoch 84/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - loss: 599.4938 - mae: 20.7972
Epoch 85/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - loss: 574.0081 - mae: 20.1583
Epoch 86/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - loss: 550.5654 - mae: 19.7375
Epoch 87/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - loss: 562.1747 - mae: 20.1455
Epoch 88/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 528.5079 - mae: 19.2561
Epoch 89/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - loss: 505.9607 - mae: 18.8354
Epoch 90/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - loss: 506.8746 - mae: 18.7808
Epoch 91/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - loss: 507.8424 - mae: 19.0444
Epoch 92/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - loss: 470.9645 - mae: 18.0480
Epoch 93/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step - loss: 470.2949 - mae: 17.8965
Epoch 94/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - loss: 468.7146 - mae: 17.9255
Epoch 95/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step - loss: 462.8560 - mae: 17.8820
Epoch 96/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 459.9105 - mae: 17.7297
Epoch 97/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step - loss: 425.7850 - mae: 17.0402
Epoch 98/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step - loss: 409.1296 - mae: 16.8364
Epoch 99/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - loss: 424.0735 - mae: 16.9378
Epoch 100/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - loss: 393.1984 - mae: 16.2383
Epoch 101/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - loss: 411.4043 - mae: 16.6666
Epoch 102/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 748us/step - loss: 370.2332 - mae: 15.6884
Epoch 103/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 736us/step - loss: 382.4944 - mae: 15.9756
Epoch 104/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - loss: 393.0427 - mae: 16.2849
Epoch 105/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - loss: 384.0176 - mae: 16.0237
Epoch 106/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step - loss: 386.6281 - mae: 16.2731
Epoch 107/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 365.0723 - mae: 15.8313
Epoch 108/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - loss: 355.0873 - mae: 15.5014
Epoch 109/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - loss: 357.0982 - mae: 15.5296
Epoch 110/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - loss: 344.4154 - mae: 15.0351
Epoch 111/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - loss: 318.0921 - mae: 14.4981
Epoch 112/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - loss: 324.5723 - mae: 14.6970
Epoch 113/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - loss: 336.5122 - mae: 15.0320
Epoch 114/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 316.6070 - mae: 14.1853
Epoch 115/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - loss: 317.6867 - mae: 14.5122
Epoch 116/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - loss: 312.3185 - mae: 14.2787
Epoch 117/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - loss: 320.2143 - mae: 14.6314
Epoch 118/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step - loss: 345.8488 - mae: 15.1573
Epoch 119/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - loss: 304.0995 - mae: 14.1753
Epoch 120/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - loss: 307.7211 - mae: 14.2312
Epoch 121/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - loss: 311.4717 - mae: 14.3511
Epoch 122/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - loss: 307.7068 - mae: 14.3208
Epoch 123/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 288.6458 - mae: 13.8021
Epoch 124/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step - loss: 285.2742 - mae: 13.7491
Epoch 125/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - loss: 281.3303 - mae: 13.6180
Epoch 126/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - loss: 291.5982 - mae: 13.9330
Epoch 127/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step - loss: 290.3950 - mae: 13.6895
Epoch 128/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 699us/step - loss: 291.2182 - mae: 13.8173
Epoch 129/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 699us/step - loss: 305.8086 - mae: 14.1395
Epoch 130/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - loss: 280.3597 - mae: 13.5797
Epoch 131/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - loss: 263.3620 - mae: 13.2281
Epoch 132/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - loss: 278.1704 - mae: 13.2775
Epoch 133/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - loss: 286.7703 - mae: 13.7370
Epoch 134/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - loss: 281.8680 - mae: 13.7085
Epoch 135/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - loss: 284.9446 - mae: 13.6538
Epoch 136/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - loss: 282.6021 - mae: 13.6432
Epoch 137/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - loss: 277.9332 - mae: 13.2859
Epoch 138/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - loss: 279.8586 - mae: 13.3809
Epoch 139/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - loss: 284.3399 - mae: 13.6441
Epoch 140/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - loss: 289.2578 - mae: 13.8115
Epoch 141/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - loss: 262.2246 - mae: 13.0247
Epoch 142/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 283.2437 - mae: 13.7339
Epoch 143/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 291.7484 - mae: 13.8815
Epoch 144/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - loss: 267.8383 - mae: 13.1431
Epoch 145/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - loss: 293.0884 - mae: 13.7201
Epoch 146/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - loss: 284.9238 - mae: 13.5840
Epoch 147/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - loss: 287.7185 - mae: 13.6465
Epoch 148/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - loss: 265.5150 - mae: 12.9769
Epoch 149/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 264.3495 - mae: 12.9854
Epoch 150/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - loss: 270.5816 - mae: 13.2908
Epoch 151/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - loss: 272.8199 - mae: 13.3931
Epoch 152/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - loss: 273.4170 - mae: 13.3003
Epoch 153/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - loss: 279.3739 - mae: 13.5019
Epoch 154/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 266.0265 - mae: 13.1316
Epoch 155/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 699us/step - loss: 257.9334 - mae: 12.9872
Epoch 156/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 262.6601 - mae: 13.1867
Epoch 157/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - loss: 269.8087 - mae: 13.2477
Epoch 158/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - loss: 262.9371 - mae: 13.0410
Epoch 159/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 266.8136 - mae: 13.0490
Epoch 160/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step - loss: 245.1266 - mae: 12.5770
Epoch 161/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - loss: 257.5096 - mae: 12.7936
Epoch 162/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - loss: 275.1913 - mae: 13.2802
Epoch 163/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - loss: 258.6859 - mae: 13.0142
Epoch 164/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - loss: 276.8643 - mae: 13.3882
Epoch 165/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - loss: 263.6452 - mae: 13.0213
Epoch 166/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - loss: 268.4751 - mae: 13.2623
Epoch 167/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - loss: 268.6959 - mae: 13.1120
Epoch 168/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - loss: 252.4655 - mae: 12.8020
Epoch 169/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - loss: 252.7878 - mae: 12.6941
Epoch 170/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 270.8718 - mae: 13.3061
Epoch 171/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - loss: 259.9625 - mae: 13.0031
Epoch 172/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 712us/step - loss: 240.4408 - mae: 12.4964
Epoch 173/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - loss: 253.6317 - mae: 12.7846
Epoch 174/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step - loss: 267.5257 - mae: 13.2515
Epoch 175/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - loss: 263.8495 - mae: 13.0919
Epoch 176/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - loss: 268.0868 - mae: 13.1706
Epoch 177/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step - loss: 244.9089 - mae: 12.6010
Epoch 178/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - loss: 229.9026 - mae: 12.0894
Epoch 179/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 741us/step - loss: 253.2546 - mae: 12.7754
Epoch 180/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 764us/step - loss: 242.8766 - mae: 12.4754
Epoch 181/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 704us/step - loss: 252.7493 - mae: 12.8214
Epoch 182/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - loss: 240.3644 - mae: 12.3317
Epoch 183/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - loss: 246.7629 - mae: 12.5261
Epoch 184/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 243.7300 - mae: 12.5726
Epoch 185/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - loss: 245.6857 - mae: 12.5967
Epoch 186/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - loss: 251.1817 - mae: 12.7403
Epoch 187/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 263.4828 - mae: 13.1015
Epoch 188/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - loss: 264.7808 - mae: 13.1942
Epoch 189/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - loss: 243.8291 - mae: 12.6014
Epoch 190/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - loss: 250.1084 - mae: 12.5841
Epoch 191/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - loss: 269.8845 - mae: 13.2533
Epoch 192/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - loss: 249.0576 - mae: 12.8294
Epoch 193/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - loss: 234.7634 - mae: 12.2783
Epoch 194/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - loss: 266.6472 - mae: 13.0857
Epoch 195/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - loss: 254.5238 - mae: 12.8719
Epoch 196/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 250.9543 - mae: 12.6191
Epoch 197/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - loss: 247.6309 - mae: 12.8452
Epoch 198/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - loss: 261.8007 - mae: 13.1258
Epoch 199/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step - loss: 242.4440 - mae: 12.4749
Epoch 200/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - loss: 242.8541 - mae: 12.3836
Epoch 201/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - loss: 250.9532 - mae: 12.9312
Epoch 202/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - loss: 240.6276 - mae: 12.5145
Epoch 203/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - loss: 230.9975 - mae: 12.1810
Epoch 204/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 249.0927 - mae: 12.7352
Epoch 205/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - loss: 234.6639 - mae: 12.2656
Epoch 206/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - loss: 242.2956 - mae: 12.5161
Epoch 207/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - loss: 243.2328 - mae: 12.6757
Epoch 208/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - loss: 217.0155 - mae: 12.0335
Epoch 209/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - loss: 225.3914 - mae: 12.0760
Epoch 210/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - loss: 239.7347 - mae: 12.6072
Epoch 211/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - loss: 243.3554 - mae: 12.5549
Epoch 212/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - loss: 239.3747 - mae: 12.4932
Epoch 213/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - loss: 236.5874 - mae: 12.3898
Epoch 214/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - loss: 237.8963 - mae: 12.4473
Epoch 215/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - loss: 227.4144 - mae: 12.1641
Epoch 216/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - loss: 226.5212 - mae: 12.0831
Epoch 217/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - loss: 219.0877 - mae: 12.0581
Epoch 218/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 756us/step - loss: 227.7011 - mae: 12.0669
Epoch 219/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - loss: 233.8312 - mae: 12.4052
Epoch 220/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - loss: 239.0298 - mae: 12.4663
Epoch 221/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - loss: 225.1733 - mae: 12.0215
Epoch 222/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step - loss: 224.7432 - mae: 12.0956
Epoch 223/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - loss: 214.1133 - mae: 11.8497
Epoch 224/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 207.6078 - mae: 11.4778
Epoch 225/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - loss: 224.6765 - mae: 11.9083
Epoch 226/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - loss: 237.3385 - mae: 12.4079
Epoch 227/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - loss: 217.8784 - mae: 11.8706
Epoch 228/1000

In [27]:
modelo.save("students_1x1_linear.keras")